### ISSUE TITLE
f3 covariance matrix

### ISSUE THREAD

**Issue by aflorebe** [juliayyan/PhylogeneticTrees.jl#13]
Hello,

First, I would like to thank you for this exciting and interesting approach. 

I am trying to run the method with my data, but I do not fully understand how to obtain the covariance matrix of the f3 statistics. What would be the best way to calculate this matrix? 

I hope you could help me.

Thank you in advance

**Comment by juliayyan** [comment]
You can run [qpGraph 6.0](https://github.com/DReichLab/AdmixTools) with the following settings:

fstatsname: fStats.txt
doanalysis:	NO

This will output all relevant f3 statistics as well as covariances for the pair of f3 statistics in a single file. The first part of the file will have 3 columns, reflecting the f-statistics f3(base; population 1, population 2) and the second 4 columns reflecting the covariance of the two f3-statistics f3(base; population 1, population 2) and f3(base, population 3, population 4)

This still requires that you specify a set of vertices and labels with the populations you are interested in modeling. Note that the base population will be the first population that you specify a vertex and a label for.

We'll update the documentation with this info.

**Comment by aflorebe** [comment]
Awesome! I did not actually know about that option in the latest version of AdmixTools.

Thank you so much.
